version: '3'

services:
  demoapp:
    platform: linux/x86_64
    build:
      context: .
      args:
        JAR_FILE: build/libs/demo-0.0.1-SNAPSHOT.jar
    ports:
      - "8085:8085"
    environment:
      SPRINGDOC_SWAGGER-UI_PATH: /
